/*
 * SPDX-License-Identifier: GPL-2.0-or-later
 * Copyright (C) 2026 Noro. Part of the StreamGearMixer OBS plugin. See LICENSE.
 *
 * obsconfig.h stub — normally generated by obs-studio's CMake.
 * Only the macros referenced by the public libobs headers are needed here.
 * LIBOBS_API_*_VER lives in obs-config.h (from the obs-studio source tree),
 * so keep the checked-out obs-studio tag in sync with the installed OBS.
 */
#pragma once

#define OBS_DATA_PATH "data"
#define OBS_PLUGIN_PATH "obs-plugins"
#define OBS_PLUGIN_DESTINATION "obs-plugins/64bit"
#define OBS_INSTALL_PREFIX ""
#define OBS_RELEASE_CANDIDATE 0
#define OBS_BETA 0
